apiVersion: v1
kind: Service
metadata:
  name: customer-facing-web-server
spec:
  type: ClusterIP
  ports:
  - port: 3001
    targetPort: 3001
    protocol: TCP
    name: api
  selector:
    app: customer-facing-web-server