apiVersion: v1
kind: Service
metadata:
  name: customer-manager
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: customer-manager

apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-manager
  template:
    metadata:
      labels:
        app: customer-manager
    spec:
      containers:
        - name: customer-manager
          image: customer-manager:latest
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 3000
          env:
            - name: KAFKA_URL
              value: kafka-service:9092
            - name: MONGO_URL
              value: customer-stack-mongodb:27017