apiVersion: v1
kind: Service
metadata:
  name: customer-client
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: customer-client

apiVersion: v1
kind: Service
metadata:
  name: customer-manager
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: customer-manager
